// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/26/2025, 3:32:31 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/maksimkravcov/Desktop/проекты/web-seo/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maksimkravcov/Desktop/проекты/web-seo/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maksimkravcov/Desktop/проекты/web-seo/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maksimkravcov/Desktop/проекты/web-seo/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maksimkravcov/Desktop/проекты/web-seo/src/plugins/**/*.{js,ts,mjs}","/Users/maksimkravcov/Desktop/проекты/web-seo/src/constants/**/*.{js,ts,mjs}","/Users/maksimkravcov/Desktop/проекты/web-seo/src/types/**/*.{js,ts,mjs}","/Users/maksimkravcov/Desktop/проекты/web-seo/src/composables/**/*.{js,ts,mjs}","/Users/maksimkravcov/Desktop/проекты/web-seo/src/utils/**/*.{js,ts,mjs}","/Users/maksimkravcov/Desktop/проекты/web-seo/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maksimkravcov/Desktop/проекты/web-seo/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/maksimkravcov/Desktop/проекты/web-seo/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/maksimkravcov/Desktop/проекты/web-seo/src/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;